

pub const GLOBAL_STATE_SEED: &str = "GLOBAL-STATE-SEED";
pub const NATIVE_VAULT_SEED: &[u8] = b"RA-NATIVE-VAULT-SEED";
pub const RAFFLE_SEED: &str = "ONE-RAFFLE-SEED";
pub const BUYER_STATE_SEED: &str = "BUYER-STATE-SEED";
pub const AUCTION_SEED: &str = "ONE-AUCTION-SEED";
pub const ZZZ_VAULT_SEED: &str = "RA-PAY-VAULT-SEED";
pub const REWARD_VAULT_SEED: &str = "RA-REWARD-VAULT-SEED";
pub const NFT_VAULT_SEED: &str = "RA-AUCTION-NFT-VAULT-SEED";
pub const BIDDER_STATE_SEED: &str = "RA-BIDDER-STATE-SEED";

pub const LAMPORTS_PER_SOL: u64 = 1000000000;
pub const CANCEL_BID_PRICE: u64 = 33000000; //0.033 * LAMPORTS_PER_SOL;
